name: Deploy Node backend to Azure Web App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  APP_NAME: Fitness-app   # <-- Azure'daki App Service adını BURAYA birebir yaz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node versiyonunu App Service'in Node imajıyla uyumlu tut (20.x).
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Temiz kurulum (package-lock.json varsa "ci", yoksa "install" da olur)
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # İsteğe bağlı: basit bir build adımı yoksa atlanır (sende sadece backend var)
      # - name: Build
      #   run: npm run build

      # Deploy: node_modules dahil çalışma klasörünü upload eder
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
