name: Deploy Node backend to Azure Web App

on:
  push:
    branches: [ master ]      # dalın main ise main yaz
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (backend)
        working-directory: fitness-backend
        run: npm ci

      # İstersen build scriptin yoksa bu adımı atlar
      - name: Build (optional)
        working-directory: fitness-backend
        run: |
          if jq -e '.scripts.build' package.json >/dev/null; then
            npm run build
          else
            echo "no build script"
          fi

      # DİKKAT: node_modules'ı hariç tutmuyoruz
      - name: Zip backend WITH node_modules
        run: |
          cd fitness-backend
          zip -r ../app.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D209808A498E4F39B32201A1841C6068 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4908380AA5B94490890C018366C73D1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_53090F00761E44949A51B8580F07AF27 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: <APP_SERVICE_ADIN>      # Fitness-app’in tam adı
          slot-name: Production
          package: app.zip

