name: Deploy Node.js app to Azure Web App (OIDC)

on:
  push:
    branches: [ master, main ]

# OIDC ile token alabilmek için GEREKLİ
permissions:
  id-token: write
  contents: read

env:
  APP_NAME: Fitness-app          # Azure Web App adın (Portal’da görünen)
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # İstersen: test, lint vs. (opsiyonel)
      - name: Install dependencies (prod only)
        run: npm ci --omit=dev

      - name: Build (if present)
        run: npm run build --if-present

      # build artefact’ını deploy job’ına aktar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./
          if-no-files-found: warn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # OIDC iznini job seviyesinde de verebiliriz (üstte global var ama bu da ok)
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Setup Node (for any build scripts during deploy)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          # Bu üç değeri repo Secrets’a eklemelisin
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: ./
          # slot: production  # (slot kullanıyorsan aç)

